plugins {
    id 'java'
    id 'groovy'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}

group = 'com.projectbank'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.liquibase:liquibase-core'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'org.hibernate.orm:hibernate-core:6.5.2.Final'
    implementation 'org.springframework.boot:spring-boot-starter-logging'
    implementation 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

}

test {
    useJUnitPlatform()
}

bootJar {
    archiveFileName = "projectbank-loan.jar"
}

springBoot {
    mainClass = 'com.projectbank.loan.LoanServiceApplication'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact(tasks.bootJar) {
                classifier = 'boot'
            }

            groupId = project.group
            artifactId = project.name
            version = project.version
        }
    }

    repositories {
        maven {
            url = System.getenv("CI_NEXUS_URL")
            allowInsecureProtocol = true
            credentials {
                username = System.getenv("CI_NEXUS_USER")
                password = System.getenv("CI_NEXUS_PASSWORD")
            }
        }
    }
}
