CREATE TABLE IF NOT EXISTS security_logs (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMP,
    method  VARCHAR(20),
    ip_address  VARCHAR(45),
    device_info VARCHAR(255),
    is_active BOOLEAN NOT NULL
);