
--CREATE TABLE IF NOT EXISTS biometric_settings (
--    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--    user_id INT NOT NULL,
--    biometric_enabled BOOLEAN NOT NULL,
--    last_used TIMESTAMP,
--    device_info VARCHAR(255),
--    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id)
--);