plugins {
    id 'java'
    id 'groovy'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}

group = 'com.projectbank'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact(tasks.bootJar) {
                classifier = 'boot'
            }

            groupId = project.group
            artifactId = project.name
            version = project.version
        }
    }

    repositories {
        maven {
            url = System.getenv("CI_NEXUS_URL")
            allowInsecureProtocol = true
            credentials {
                username = System.getenv("CI_NEXUS_USER")
                password = System.getenv("CI_NEXUS_PASSWORD")
            }
        }
    }
}

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Database
    implementation 'org.postgresql:postgresql:42.7.5'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // Связка Lombok и MapStruct
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Liquibase
    implementation 'org.liquibase:liquibase-core'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'net.lbruun.springboot:preliquibase-spring-boot-starter:1.5.0'

    testImplementation "org.springframework.kafka:spring-kafka-test"
    testImplementation "org.testcontainers:kafka"
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.kafka:spring-kafka-test"
    testImplementation "org.testcontainers:postgresql:1.19.1"
    testImplementation "com.h2database:h2:2.2.222"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}

tasks.named('test') {
    useJUnitPlatform()
}