server:
  port: ${SERVER_PORT:8083}
  forward-headers-strategy: framework
  servlet:
    context-path: /email-notification-ms

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:email-notification-ms}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:notification-group}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: ${KAFKA_CONSUMER_TRUSTED_PACKAGES:ru.globus.emailnotificationms.dto.request}
        spring.json.use.type.headers: true
        spring.json.type.mapping: ${KAFKA_CONSUMER_TYPE_MAPPING:EmailNotificationDto:ru.globus.emailnotificationms.dto.request.EmailNotificationDto}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.use.type.headers: true
        spring.json.type.mapping: ${KAFKA_PRODUCER_TYPE_MAPPING:NotificationResponse:ru.globus.emailnotificationms.dto.response.NotificationResponse}
    topic:
      email-notifications: ${KAFKA_TOPIC_EMAIL_NOTIFICATIONS:email-notifications-topic}
      notification-responses: ${KAFKA_TOPIC_NOTIFICATION_RESPONSES:notification-responses-topic}
    listener:
      missing-topics-fatal: ${KAFKA_MISSING_TOPICS_FATAL:false}
      ack-mode: BATCH
      type: BATCH

logging:
  config: classpath:logback.xml
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework: ${LOGGING_LEVEL_SPRING:DEBUG}
    org.springframework.kafka: ${LOGGING_LEVEL_KAFKA:DEBUG}
    ru.globus.emailnotificationms: ${LOGGING_LEVEL_APP:DEBUG}
  file:
    path: logs
    name: logs/email-notification-ms.log

email:
  mailProperties:
    host: ${EMAIL_HOST:}
    mail-to: ${EMAIL_TO:}
    port: ${EMAIL_PORT:}
    transport:
      protocol: ${EMAIL_PROTOCOL:smtp}
    smtp:
      auth: ${EMAIL_SMTP_AUTH:true}
      ssl:
        enable: ${EMAIL_SMTP_SSL_ENABLE:true}
    debug: ${EMAIL_DEBUG:true}
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    mail-from: ${EMAIL_FROM:}
    subject: ${EMAIL_SUBJECT:"Notification from Project Bank:"}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus  # Какие endpoint доступны
  endpoint:
    health:
      show-details: always             # Детализация health-статуса
    info:
      env:
        include: app.version           # Какие данные включать в /info
  server:
    port: 8099

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
    display-operation-id: true
    try-it-out-enabled: true
