spring.application.name=eapi-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5428/demoDB
spring.datasource.username=usr
spring.datasource.password=pwd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Flyway
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

#Logging db properties
eapiservice.logging.dburl=jdbc:postgresql://localhost:5428/demoDB
eapiservice.logging.dbusr=usr
eapiservice.logging.dbpwd=pwd
