services:
  customer-service:
    build:
      context: .
    container_name: customer-service
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
    ports:
      - "8087:8080"
    restart: unless-stopped
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
