plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}

group = 'globus.bank.risk'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

ext {
    set('springCloudVersion', "2025.0.0")
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    //Gens
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation "org.mapstruct:mapstruct:1.6.3"
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.1.Final'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.8"
    implementation 'io.micrometer:micrometer-registry-prometheus:1.15.3'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'


}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact(tasks.bootJar) {
                classifier = 'boot'
            }

            groupId = project.group
            artifactId = project.name
            version = project.version
        }
    }

    repositories {
        maven {
            url = System.getenv("CI_NEXUS_URL")
            allowInsecureProtocol = true
            credentials {
                username = System.getenv("CI_NEXUS_USER")
                password = System.getenv("CI_NEXUS_PASSWORD")
            }
        }
    }
}

sourceSets.main.java.srcDirs += "build/generated/sources/annotationProcessor/java/main"

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Amapstruct.defaultComponentModel=spring']
}

tasks.named('test') {
    useJUnitPlatform()
}
